### ISSUE TITLE
slack-post-resource `in` method should produce the timestamp file

### ISSUE THREAD

**Issue by xNok** [jleben/slack-chat-resource#3]
I want to be able to post all the notification associated to a build in the thread associated to the build.
For instance, once the deployement is completed the notification goes to the associatedd build thread. To do so we can use two ressources `jakobleben/slack-post-resource`. The furst one `slack-out` is associated to the build, by using **passed** we make sure that slack-out is symchonised with the sucessfull builds that need te be deployed. The second ressource `slack-out-thread` is ussed to post anymessage that is not a build.

```
name: deploy
- get: slack-out
  passed: [build]
- put: slack-out-thread
      params:
        message:
            thread_ts: "{{slack-out/timestamp}}"
```

However to get this feature to work, I would need that ` get: slack-out` produce the file slack-out/timestamp.

Thanks for considering this feature request
