### ISSUE TITLE
slack-read-resource seems to get in a stuck state after long inactivity

### ISSUE THREAD

**Issue by renatolond** [jleben/slack-chat-resource#6]
Hi!

We use slack-read-resource to trigger builds. It works very well for our most deployed project, however, for the projects that we deploy once a month or less, it seems that after some time it gets into a stuck state. Meaning, I send the same message it usually detects, but it does not detect the message.
If I try to manually trigger through concourse UI, I see a "checking successfully", but nothing changes.
If we re-deploy the pipeline to concourse, the resource starts working again.

The slack-post-resource keeps working, if we trigger a build manually it answer to last message the read resource detected, a month and something ago.

We're using concourse v5.5.1. This is the config for the resource:

```
- name: slack-trigger
  type: slack-read-resource
  check_every: 15s
  source:
    token: xxx
    channel_id: yyyy
    matching:
      text_pattern: 'Concourse deploy'
```
